
/* Contenu de la table "activite"  */

INSERT INTO activite (nom_activite, descript_activite) 
	VALUES 	("Aéroport - Prendre un billet", NULL),
			("Aéroport - Repérage et fiche de douane", NULL),
			("Aéroport - Embarquer", NULL),
			("Bâtiment - Calcul de la surface d'une pièce", NULL),
			("Bâtiment - Activité réfection d'un mur", NULL),
			("Restauration - Prendre une réservation", NULL),
			("Restauration - Prendre une commande", NULL),
			("Restauration - Ecrire un menu", NULL),
			("Restauration - Inventaire de stock", NULL),
			("Hygiène des locaux - Dosage", NULL),
			("Hygiène des locaux - Signaletique danger", NULL),
			("Hygiène des locaux - nettoyer une piece", NULL),
			("Carte d identite - Identifier les pieces constitutives", NULL),
			("Carte d'identite - Trouver le lieu de renouvellement", NULL),
			("Carte d'identite - Se reperer dans les transports", NULL),
			("Carte d'identite - Se reperer dans la mairie", NULL),
			("Citoyenneté - élections présidentielles", NULL),
			("Développement durable - Le tri des déchets", NULL),
			("Développement durable - le vocabulaire du développement durable", NULL),
			("Développement durable - Le réchauffement climatique", NULL),
			("Blanchisserie - Machine à laver et codification vêtements", NULL),
			("Blanchisserie - Le tri du linge en entreprise", NULL),
			("Budget de la vie quotidienne - Au supermarché", NULL),
			("Budget de la vie quotidienne - Crédit à la consommation", NULL),
			("Budget de la vie quotidienne - Gérer son budget", NULL),
			("Budget de la vie quotidienne - Lire son Bulletin de salaire", NULL),
			("Espace verts - Planter des laitues 1", NULL),
			("Espace verts - Planter des laitues 2", NULL),
			("Espace verts - Démarrer une tronçonneuse", NULL),
			("Garde d'enfants - Organiser la garde", NULL),
			("Garde d'enfants - Preparer les repas", NULL),
			("Garde d'enfants - Employer une assistante maternelle : contrat de travail", NULL),
			("Logement - Etat des lieux", NULL),
			("Logement - Le changement d'adresse", NULL),
			("Logement - Rechercher un appartement", NULL),
			("Mode d'emploi et notice - Montage d'un meuble", NULL),
			("Mode d'emploi et notice - Notice d'un médicament", NULL),
			("Risques professionnels - Procédure d'arrêt d'urgence", NULL),
			("Risques professionnels - Lire un plan d'évacuation", NULL),
			("Risques professionnels - L'arbre des causes", NULL),
			("Se déplacer - Consulter un index des rues", NULL),
			("Se déplacer - Réserver un billet de train sur un automate 1", NULL),
			("Se déplacer - Réserver un billet de train sur un automate 2", NULL),
			("Se déplacer - Utiliser un GPS ", NULL),
			("Se déplacer - Utiliser des moyens de transport multiples", NULL),
			("Se déplacer - Simulation sur autoroute : lecture rapide des panneaux", NULL),
			("Se déplacer en bus", NULL),
			("Préparer son trajet Rouen Lyon", NULL),
			("Procédure d'arrêt d'urgence", NULL),
			("Plan d'évacuation", NULL);
